# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ee1c4818b437b60800affc66a3436f9c9cd54160966595f4c5ce5e73e9a3ab131873a95ec9f3144a5a08688e773d8e45c1924586fb49e0699002610720971ad

test:
  secret_key_base: c6791c061422117d805f102fc9202bb52550e0b9f6b3ec5c615d1f3f3a69a061316cc22bb730368aac7f9fa3f09a528ac706b34491b781bfe92da6916a5b0d3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
